name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # --- НОВЫЙ КЛЮЧЕВОЙ БЛОК ---
    # Явно даем права этому процессу на чтение кода и запись пакетов
    permissions:
      contents: read
      packages: write
    # ---------------------------

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate lowercase docker tag
        id: meta
        run: |
          echo "repo_tag=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Используем стандартный GITHUB_TOKEN, так как теперь у него есть права
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.meta.outputs.repo_tag }}:${{ github.sha }}